#!/bin/sh
# A Dock-able launcher that BUILDS master and then runs it.
#
#   extra/make-dev-launcher.sh            -> ~/Applications/HelioFITS Studio (dev).app
#   extra/make-dev-launcher.sh /some/dir  -> /some/dir/HelioFITS Studio (dev).app
#   CHECKOUT=/a/worktree extra/make-dev-launcher.sh   -> builds that checkout instead
#
# It builds the repository's main checkout, whichever worktree this script is run from, because
# that is where master lives, and running it from a worktree used to point the Dock at that
# worktree for good. Merges are pushed to GitHub rather than into that checkout, so each click
# first fast-forwards a clean master from origin, then runs `ant jar` and starts the jar it just
# built. Ant is incremental, so an unchanged tree costs a couple of seconds and a changed one costs
# a compile.
#
# The Dock will not hold a shell script, only a bundle, which is the whole reason this exists.
# The bundle is three files and no build system of its own: a plist, the script below, and the
# app's icon so it is recognisable beside the released one.
set -eu

here=$(cd "$(dirname "$0")/.." && pwd)
# The main checkout is the parent of the git directory every worktree shares.
main=$(dirname "$(git -C "$here" rev-parse --path-format=absolute --git-common-dir)")
checkout=${CHECKOUT:-$main}
dest=${1:-$HOME/Applications}
app="$dest/HelioFITS Studio (dev).app"

mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"

cat > "$app/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>HelioFITS Studio (dev)</string>
    <key>CFBundleDisplayName</key><string>HelioFITS Studio (dev)</string>
    <key>CFBundleIdentifier</key><string>org.helioviewer.jhv.hfstudio.dev</string>
    <key>CFBundleExecutable</key><string>launch</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>dev</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <!-- A dev checkout under ~/Documents is TCC-protected, and an app bundle does not inherit the
         Terminal's permission to read it: without this the stub gets EPERM before it can exec
         anything, silently. With it, macOS has a reason to show, and to remember, the prompt. -->
    <key>NSDocumentsFolderUsageDescription</key>
    <string>HelioFITS Studio (dev) runs the build in your development checkout.</string>
    <key>NSDesktopFolderUsageDescription</key>
    <string>HelioFITS Studio (dev) runs the build in your development checkout.</string>
    <key>NSDownloadsFolderUsageDescription</key>
    <string>HelioFITS Studio (dev) runs the build in your development checkout.</string>
    <!-- One tile, not two: the stub execs java in place rather than spawning it, so the bundle
         does not also sit in the Dock. That tile reads its name and icon from the keys above,
         but only because java is exec'd through a symlink inside this bundle -- see the stub. -->
    <key>LSUIElement</key><false/>
</dict>
</plist>
PLIST

cat > "$app/Contents/MacOS/launch" <<LAUNCH
#!/bin/sh
# Generated by extra/make-dev-launcher.sh. Edit the checkout path here if you move it.
checkout="$checkout"
buildlog="\$HOME/.hfstudio-dev-build.log"

say() {
    osascript -e "display dialog \"\$1\" with title \"HelioFITS Studio (dev)\" buttons {\"OK\"} default button 1 with icon caution" >/dev/null 2>&1
}

# A checkout under ~/Documents, ~/Desktop or ~/Downloads is TCC-protected, and an app bundle does
# not inherit the Terminal's permission to read it. The failure is otherwise completely silent:
# the Dock icon bounces once and nothing happens, because the shell cannot even stat the script.
if [ ! -r "\$checkout/run.sh" ]; then
    say "Cannot read the build at:

\$checkout

macOS protects that folder and this launcher has not been allowed into it.

System Settings > Privacy & Security > Full Disk Access, press +, add HelioFITS Studio (dev). Or move the checkout outside Documents, Desktop and Downloads and run extra/make-dev-launcher.sh again."
    exit 1
fi

cd "\$checkout" || exit 1

# LaunchServices hands over a login PATH, not an interactive one, so Homebrew may be missing from
# it; and ant needs a JDK it can find without a profile having exported one.
PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
export PATH
if [ -z "\${JAVA_HOME:-}" ]; then
    JAVA_HOME=\$(/usr/libexec/java_home -v 25 2>/dev/null) && export JAVA_HOME
fi

# Merges are pushed to GitHub, not into this checkout, so bring it up to origin/master first.
# Fast-forward only, and only on a clean master: anything else is someone's work in progress, and
# the build then runs on what is there rather than touch it. The fetch is best effort (a stalled
# connection is given up after 10 s under 1 kB/s), and the fast-forward is tried either way,
# because every push from a worktree already moves the origin/master this checkout can see.
# Everything is written to the build log: this step once failed without a trace.
{
    echo "== \$(date '+%Y-%m-%d %H:%M:%S') updating \$checkout"
    if [ "\$(git rev-parse --abbrev-ref HEAD)" != master ]; then
        echo "not on master: building it as it is"
    elif [ -n "\$(git status --porcelain --untracked-files=no)" ]; then
        echo "master has uncommitted changes: building it as it is"
    else
        git -c http.lowSpeedLimit=1000 -c http.lowSpeedTime=10 fetch origin master ||
            echo "fetch failed: using the origin/master already known here"
        git merge --ff-only origin/master || echo "could not fast-forward: building it as it is"
    fi
    echo "== building \$(git log -1 --format='%h %s')"
} >"\$buildlog" 2>&1

if ! command -v ant >/dev/null 2>&1; then
    say "ant is not on the path this launcher was given, so the build cannot run.

Install it (brew install ant) or launch from a terminal instead."
    exit 1
fi

# The build is silent and takes long enough that a dead Dock icon looks broken. A notification
# costs nothing and does not steal focus the way a dialog would.
osascript -e 'display notification "Updating master and building…" with title "HelioFITS Studio (dev)"' >/dev/null 2>&1

if ! ant jar >>"\$buildlog" 2>&1; then
    say "The build failed. Opening the log.

Nothing was launched, so what is running (if anything) is still the previous build."
    open -e "\$buildlog" >/dev/null 2>&1
    exit 1
fi

if [ "\$(git rev-parse HEAD 2>/dev/null)" != "\$(git rev-parse origin/master 2>/dev/null)" ]; then
    osascript -e "display notification \"This is \$(git log -1 --format=%h), not the newest master. The build log says why.\" with title \"HelioFITS Studio (dev)\"" >/dev/null 2>&1
fi

# run.sh is not used, and cannot be: an unsigned bundle is refused ("Operation not permitted")
# when it opens a script inside the protected tree, whether it execs it directly or hands it to
# /bin/sh. Reading DATA there is fine -- ant runs the whole build from it -- so the launch is
# done here instead, and the only thing reached for in the checkout is the jar, opened by a java
# that lives outside it. This is run.sh's last line and nothing else.
JAVA="\${JAVA_HOME:+\$JAVA_HOME/bin/java}"
[ -x "\$JAVA" ] || JAVA=\$(command -v java 2>/dev/null)
if [ -z "\$JAVA" ]; then
    say "No Java 25 or newer was found, so the build cannot be started.

Install Temurin 25 from adoptium.net, or brew install openjdk@25."
    exit 1
fi
# The exec below replaces this stub, so the process that ends up holding the Dock tile is the
# JDK's own java binary, living outside this bundle. macOS names a tile after the binary it is running
# and takes the icon from whatever bundle encloses it, so the tile came out as a generic coffee
# cup labelled "java". -Xdock:name does not change that; it was never the Dock's source for the
# name.
#
# Running java through a symlink placed inside this bundle fixes both halves at once. The name
# becomes the link's own, and NSBundle resolves upwards from the executable path, so it now finds
# THIS Info.plist instead of the JDK's: CFBundleName and the icon come for free, and macOS
# reports the process as belonging to the bundle (verified with System Events), which is what
# makes Keep in Dock pin the right thing. dyld still follows the link to the real java, so the
# JDK finds its own libraries normally.
#
# Relinked on every launch so a JDK upgrade cannot leave it dangling. If the bundle is not
# writable the link is simply not made and the tile goes back to saying "java", which is why the
# -Xdock: flags are kept below as the fallback.
runner="\$(dirname "\$0")/HelioFITS Studio (dev)"
ln -sfn "\$JAVA" "\$runner" 2>/dev/null
[ -x "\$runner" ] && JAVA="\$runner"

icon="\$(cd "\$(dirname "\$0")/../Resources" 2>/dev/null && pwd)/AppIcon.icns"
exec "\$JAVA" --enable-native-access=ALL-UNNAMED -Xdock:name="HelioFITS Studio (dev)" -Xdock:icon="\$icon" -jar "\$checkout/HFStudio.jar" "\$@"
LAUNCH
chmod +x "$app/Contents/MacOS/launch"

if [ -f "$here/release/HFStudio_icon.icns" ]; then
    cp "$here/release/HFStudio_icon.icns" "$app/Contents/Resources/AppIcon.icns"
fi

# Finder caches a bundle's icon by path and does not notice a rewrite on its own.
touch "$app"
echo "Built $app"
echo "  builds and runs: $checkout"
echo "  every click fast-forwards a clean master from origin, runs 'ant jar', then starts that jar."
echo
echo "  To keep it in the Dock, drag this bundle out of Finder onto the Dock."
